source 'https://rubygems.org'
ruby '1.9.3'

gem 'sinatra', '~>1.4.4'
gem 'sinatra-contrib'
gem 'thin'
gem 'htmlentities'
gem 'slim'
gem 'omniauth-openid'
gem 'ruby-openid-apps-discovery'
gem 'datamapper'
gem 'dm-postgres-adapter'
gem 'pg'
